# Generated from ".makefile"
#  Target values for VM: ("cs" "bc")
#  Target values for INITIAL_SETUP_MODE: ("minimal" "skip")
#  Target values for CS_CROSS_SUFFIX: ("-cross" "")
#  Target values for NEXT_TARGET: ("plain-server" "plain-client-from-site" "plain-installers-from-built" "plain-site-from-installers" "plain-snapshot-at-site")
#  Target values for CLIENT_BASE: ("base" "cs-base" "bc-base")
#  Target values for WIN32_CLIENT_BASE: ("win32-base" "win32-cs-base" "win32-bc-base")
#  Target values for BUNDLE_FROM_SERVER_TARGET: ("bundle-from-server" "bundle-cross-from-server")
PKGS = main-distribution main-distribution-test
PLAIN_RACKET = racket/bin/racket
WIN32_PLAIN_RACKET = racket\racket
SETUP_MACHINE_FLAGS =
RUN_RACKET =  $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects
RUN_RACO =  $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects -N raco -l- raco
DEFAULT_SRC_CATALOG = https://pkgs.racket-lang.org
PLT_SETUP_OPTIONS = 
CPUS =
VM = bc
INITIAL_SETUP_MODE = minimal
UPDATE_PKGS_ARGS =  --all --auto --no-setup --scope installation
INSTALL_PKGS_ARGS =  $(JOB_OPTIONS) --no-setup --pkgs --skip-installed --scope installation --deps search-auto $(REQUIRED_PKGS) $(PKGS)
ALL_PLT_SETUP_OPTIONS =  $(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)
IN_PLACE_SETUP_OPTIONS =
PREFIX = 
CONFIG_PREFIX_ARGS =  --prefix=$(PREFIX) --enable-macprefix
UNIXSTYLE_CONFIG_qq =  MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS) --prefix=$(PREFIX) --enable-macprefix" CONFIG_IN_PLACE_ARGS=""
UNIX_CATALOG =  build/local/catalog
UNIX_RACO_ARGS =  $(JOB_OPTIONS) --catalog build/local/catalog --auto -i
UNIX_BASE_ARGS =  SELF_ROOT_CONFIG_FLAG="-Z" SKIP_DESTDIR_FIX="skip"
LOC_CATALOG =  build/local/pkgs-catalog
CONFIGURE_ARGS_qq =
MORE_CONFIGURE_ARGS = 
SELF_ROOT_CONFIG_FLAG = -G
SELF_FLAGS_qq =  SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)"
PLT_SETUP_OPTIONS_qq =  PLT_SETUP_OPTIONS="$(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)"
INSTALL_SETUP_ARGS =  SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" PLT_SETUP_OPTIONS="$(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
WIN32_BUILD_LEVEL = all
RACKETBC_SUFFIX = 
SRC_MAKEFILE_CONFIG = configure
CONFIG_IN_PLACE_ARGS = --disable-useprefix --enable-origtree
MORE_CROSS_CONFIGURE_ARGS =
RACKETCS_SUFFIX = cs
RACKET =
RACKET_FOR_BOOTFILES = $(RACKET)
RACKET_FOR_BUILD = $(RACKET)
RACKET_BUILT_FOR_CS = racket/src/build/racket/racket3m
MAKE_BUILD_SCHEME = checkout
PB_BRANCH =  circa-7.8.0.6-1
PB_REPO =  https://github.com/racket/pb
EXTRA_REPOS_BASE =
CS_CROSS_SUFFIX =
RACKETCS_NOSUFFIX_CONFIG =  MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS) --enable-csdefault"
PB_DIR =  racket/src/ChezScheme/boot/pb
WIN32_BOOT_ARGS =  SETUP_BOOT_MODE=--boot WIN32_BUILD_LEVEL=3m PLAIN_RACKET=racket\racket3m
WIN32_SETUP_BOOT =  -O "info@compiler/cm" -l- setup $(SETUP_BOOT_MODE) racket/src/setup-go.rkt racket/src/build/compiled ignored racket/src/build/ignored.d
CSBUILD_ARGUMENTS =  --pull --racketcs-suffix "$(RACKETCS_SUFFIX)" $(DISABLE_STATIC_LIBS) --boot-mode "$(SETUP_BOOT_MODE)" --extra-repos-base "$(EXTRA_REPOS_BASE)" -- $(GIT_CLONE_ARGS_qq)
SRC_CATALOG = $(DEFAULT_SRC_CATALOG)
DOC_SEARCH = 
SERVER = localhost
SERVER_PORT = 9440
SERVER_URL_SCHEME = http
SERVER_CATALOG_PATH =
SERVER_COLLECTS_PATH =
SERVER_HOSTS = localhost
RELEASE_MODE =
SOURCE_MODE =
VERSIONLESS_MODE =
MAC_PKG_MODE =
TGZ_MODE =
INSTALLER_OPTIONS =
PKG_SOURCE_MODE =
DISABLE_STATIC_LIBS =
INSTALLER_PRE_PROCESS_BASE64 =
INSTALLER_POST_PROCESS_BASE64 =
DIST_NAME = Racket
DIST_BASE = racket
DIST_DIR = racket
DIST_SUFFIX = 
DIST_DESC =
DIST_CATALOGS_q = ""
BUILD_STAMP = 
INSTALL_NAME =
SIGN_IDENTITY = 
OSSLSIGNCODE_ARGS_BASE64 =
README = $(SERVER_URL_SCHEME)://$(SVR_PRT)/README.txt
UPLOAD = 
CONFIG = build/site.rkt
CONFIG_MODE = default
CLEAN_MODE =
JOB_OPTIONS =
SERVE_DURING_CMD_qq = 
REQUIRED_PKGS = racket-lib
DISTRO_BUILD_PKGS = distro-build-lib
SVR_PRT = $(SERVER):$(SERVER_PORT)
SVR_CAT = $(SERVER_URL_SCHEME)://$(SVR_PRT)/$(SERVER_CATALOG_PATH)
SERVER_PKG_INSTALL_OPTIONS =
PKG_INSTALL_OPTIONS =
RECOMPILE_OPTIONS = --recompile-only
USER_CONFIG = -G build/user/config -X racket/collects -A build/user $(SETUP_MACHINE_FLAGS)
USER_RACKET = $(PLAIN_RACKET) $(USER_CONFIG)
USER_RACO = $(PLAIN_RACKET) $(USER_CONFIG) -N raco -l- raco
WIN32_RACKET = $(WIN32_PLAIN_RACKET) $(USER_CONFIG)
WIN32_RACO = $(WIN32_PLAIN_RACKET) $(USER_CONFIG) -N raco -l- raco
X_AUTO_OPTIONS = --skip-installed --deps search-auto --pkgs $(JOB_OPTIONS)
USER_AUTO_OPTIONS = --scope user $(X_AUTO_OPTIONS)
SOURCE_USER_AUTO_q = --catalog build/catalog-copy $(USER_AUTO_OPTIONS) $(SERVER_PKG_INSTALL_OPTIONS)
REMOTE_USER_AUTO = --catalog $(SVR_CAT) $(USER_AUTO_OPTIONS)
REMOTE_INST_AUTO = --catalog $(SVR_CAT) --scope installation $(X_AUTO_OPTIONS) $(PKG_INSTALL_OPTIONS) $(RECOMPILE_OPTIONS)
CONFIG_MODE_q = "$(CONFIG)" "$(CONFIG_MODE)"
BUNDLE_CONFIG = bundle/racket/etc/config.rktd
BUNDLE_RACO_FLAGS = -G bundle/racket/etc -X bundle/racket/collects -C -A bundle/user -l raco
BUNDLE_RACO = $(PLAIN_RACKET) $(BUNDLE_RACO_FLAGS)
WIN32_BUNDLE_RACO = $(WIN32_PLAIN_RACKET) $(BUNDLE_RACO_FLAGS)
IN_BUNDLE_RACO = bundle/racket/bin/raco
WIN32_IN_BUNDLE_RACO = bundle\racket\raco
PKGS_CATALOG = -U -G build/config -l- pkg/dirs-catalog --link --check-metadata --immediate
PKGS_CONFIG = -U -G build/config racket/src/pkgs-config.rkt
SERVER_COMPILE_MACHINE = -M
ANY_COMPILE_MACHINE_ARGS_qq =  SETUP_MACHINE_FLAGS="-MCR `pwd`/build/zo:" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS) --enable-crossany"
NEXT_TARGET = 
PACK_BUILT_OPTIONS =
CLIENT_BASE = base
WIN32_CLIENT_BASE = win32-base
SET_BUNDLE_CONFIG_q =  $(BUNDLE_CONFIG) "$(INSTALL_NAME)" "$(BUILD_STAMP)" "$(DOC_SEARCH)" $(DIST_CATALOGS_q)
BUNDLE_FROM_SERVER_TARGET = bundle-from-server
UPLOAD_q =  --readme "$(README)" --upload "$(UPLOAD)" --desc "$(DIST_DESC)"
DIST_ARGS_q =  --readme "$(README)" --upload "$(UPLOAD)" --desc "$(DIST_DESC)" $(RELEASE_MODE) $(SOURCE_MODE) $(VERSIONLESS_MODE) $(MAC_PKG_MODE) $(TGZ_MODE) --packed-options "$(INSTALLER_OPTIONS)" --pre-process "$(INSTALLER_PRE_PROCESS_BASE64)" --post-process "$(INSTALLER_POST_PROCESS_BASE64)" "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR) "$(DIST_SUFFIX)" "$(SIGN_IDENTITY)" "$(OSSLSIGNCODE_ARGS_BASE64)"
SITE_PATH =
FROM_SITE_ARGS =  SERVER_CATALOG_PATH=$(SITE_PATH)catalog/ SERVER_COLLECTS_PATH=$(SITE_PATH)origin/ DIST_CATALOGS_q='$(SERVER_URL_SCHEME)://$(SERVER):$(SERVER_PORT)/$(SITE_PATH)catalog/ ""' DOC_SEARCH="$(SERVER_URL_SCHEME)://$(SERVER):$(SERVER_PORT)/$(SITE_PATH)doc/local-redirect/index.html" $(PROP_ARGS)
DRIVE_ARGS_q =  $(RELEASE_MODE) $(VERSIONLESS_MODE) $(SOURCE_MODE) $(CLEAN_MODE) $(SERVER_COMPILE_MACHINE) "$(CONFIG)" "$(CONFIG_MODE)" $(SERVER) $(SERVER_PORT) "$(SERVER_HOSTS)" "$(PKGS)" "$(DOC_SEARCH)" "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR)
DRIVE_DESCRIBE =
DRIVE_CMD_q =  -l- distro-build/drive-clients $(DRIVE_DESCRIBE) $(RELEASE_MODE) $(VERSIONLESS_MODE) $(SOURCE_MODE) $(CLEAN_MODE) $(SERVER_COMPILE_MACHINE) "$(CONFIG)" "$(CONFIG_MODE)" $(SERVER) $(SERVER_PORT) "$(SERVER_HOSTS)" "$(PKGS)" "$(DOC_SEARCH)" "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR)
DOC_CATALOGS = build/built/catalog build/native/catalog
in-place:
	if [ "$(CPUS)" = "" ] ;          then $(MAKE) plain-in-place SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ;          else $(MAKE) -j $(CPUS) plain-in-place JOB_OPTIONS="-j $(CPUS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ; fi
plain-in-place:
	$(MAKE) base-config
	$(MAKE) $(VM)-$(INITIAL_SETUP_MODE)-in-place SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) $(VM)-in-place-setup RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-in-place:
	$(MAKE) win32-base-config
	$(MAKE) win32-$(VM)-$(INITIAL_SETUP_MODE)-in-place DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" PKGS_CATALOG="$(PKGS_CATALOG)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) win32-$(VM)-in-place-setup RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
plain-minimal-in-place-after-base:
	$(MAKE) pkgs-catalog DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" PKGS_CONFIG="$(PKGS_CONFIG)" SRC_CATALOG="$(SRC_CATALOG)" PLAIN_RACKET="$(PLAIN_RACKET)" PKGS_CATALOG="$(PKGS_CATALOG)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	  $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects -N raco -l- raco pkg update  --all --auto --no-setup --scope installation
	  $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects -N raco -l- raco pkg install  $(JOB_OPTIONS) --no-setup --pkgs                      --skip-installed --scope installation --deps search-auto                      $(REQUIRED_PKGS) $(PKGS)
	  $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects -N raco -l- raco setup --only-foreign-libs  $(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)
plain-in-place-setup:
	  $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects -N raco -l- raco setup  $(JOB_OPTIONS) $(PLT_SETUP_OPTIONS) $(IN_PLACE_SETUP_OPTIONS)
as-is:
	if [ "$(CPUS)" = "" ] ;          then $(MAKE) plain-as-is SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ;          else $(MAKE) -j $(CPUS) plain-as-is JOB_OPTIONS="-j $(CPUS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ; fi
plain-as-is:
	$(MAKE) plain-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) $(VM)-in-place-setup RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-as-is:
	$(MAKE) win32-base RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" VM="$(VM)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
	$(MAKE) win32-$(VM)-in-place-setup RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
unix-style:
	if [ "$(CPUS)" = "" ] ;          then $(MAKE) plain-unix-style SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" PREFIX="$(PREFIX)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" DESTDIR="$(DESTDIR)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ;          else $(MAKE) -j $(CPUS) plain-unix-style JOB_OPTIONS="-j $(CPUS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" PREFIX="$(PREFIX)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" DESTDIR="$(DESTDIR)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ; fi
plain-unix-style:
	if [ "$(PREFIX)" = "" ] ; then $(MAKE) error-need-prefix ; fi
	$(MAKE) $(VM)-base MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)  --prefix=$(PREFIX) --enable-macprefix" CONFIG_IN_PLACE_ARGS="" SELF_ROOT_CONFIG_FLAG="-Z" SKIP_DESTDIR_FIX="skip" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) set-src-catalog DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" SRC_CATALOG="$(SRC_CATALOG)" PREFIX="$(PREFIX)" DESTDIR="$(DESTDIR)"
	$(MAKE) local-catalog PREFIX="$(PREFIX)" DESTDIR="$(DESTDIR)"
	"$(DESTDIR)$(PREFIX)/bin/raco" pkg install  $(JOB_OPTIONS) --catalog  build/local/catalog --auto -i $(REQUIRED_PKGS) $(PKGS)
	cd racket/src/build && $(MAKE) fix-paths
error-need-prefix:
	: ================================================================
	: Please supply PREFIX="<dest-dir>" to set the install destination
	: ================================================================
	exit 1
local-catalog:
	"$(DESTDIR)$(PREFIX)/bin/racket" -l- pkg/dirs-catalog --check-metadata  build/local/pkgs-catalog pkgs
	"$(DESTDIR)$(PREFIX)/bin/raco" pkg catalog-copy --force --from-config  build/local/pkgs-catalog  build/local/catalog
set-src-catalog:
	if [ ! "$(SRC_CATALOG)" = "$(DEFAULT_SRC_CATALOG)" ] ; 	 then "$(DESTDIR)$(PREFIX)/bin/raco" pkg config -i --set catalogs "$(SRC_CATALOG)" ""; fi
base:
	if [ "$(CPUS)" = "" ] ;          then $(MAKE) plain-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ;          else $(MAKE) -j $(CPUS) plain-base JOB_OPTIONS="-j $(CPUS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" ; fi
plain-base:
	$(MAKE) base-config
	$(MAKE) $(VM)-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-base:
	$(MAKE) win32-base-config
	$(MAKE) win32-$(VM)-base RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
base-config:
	mkdir -p build/config
	echo '#hash((links-search-files . ()))' > build/config/config.rktd
win32-base-config:
	IF NOT EXIST build\config cmd /c mkdir build\config
	cmd /c echo #hash((links-search-files . ())) > build\config\config.rktd
bc:
	$(MAKE) bc-in-place SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc:
	$(MAKE) win32-bc-in-place DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bc-in-place:
	$(MAKE) in-place VM=bc SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc-in-place:
	$(MAKE) win32-in-place VM=bc DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bc-as-is:
	$(MAKE) as-is VM=bc SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" CPUS="$(CPUS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc-as-is:
	$(MAKE) win32-as-is VM=bc RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bc-unix-style:
	$(MAKE) unix-style VM=bc SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" PREFIX="$(PREFIX)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" DESTDIR="$(DESTDIR)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bc-minimal-in-place:
	$(MAKE) bc-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) plain-minimal-in-place-after-base PLAIN_RACKET=racket/bin/racket$(RACKETBC_SUFFIX) DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" PKGS="$(PKGS)" PKGS_CATALOG="$(PKGS_CATALOG)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc-minimal-in-place:
	$(MAKE) win32-bc-base PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" JOB_OPTIONS="$(JOB_OPTIONS)"
	$(MAKE) plain-minimal-in-place-after-base PLAIN_RACKET=racket\racket$(RACKETBC_SUFFIX) DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" PKGS="$(PKGS)" PKGS_CATALOG="$(PKGS_CATALOG)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bc-skip-in-place:
	$(MAKE) bc-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc-skip-in-place:
	$(MAKE) win32-bc-base PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" JOB_OPTIONS="$(JOB_OPTIONS)"
bc-in-place-setup:
	$(MAKE) plain-in-place-setup PLAIN_RACKET=racket/bin/racket$(RACKETBC_SUFFIX) IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc-in-place-setup:
	$(MAKE) plain-in-place-setup PLAIN_RACKET=racket\racket$(RACKETBC_SUFFIX) IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bc-base:
	$(MAKE) racket/src/build/Makefile CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)"
	cd racket/src/build && $(MAKE) reconfigure
	cd racket/src/build && $(MAKE) racket-variant  SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)"
	cd racket/src/build && $(MAKE) install-racket-variant   SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)"  PLT_SETUP_OPTIONS="$(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-bc-base:
	$(MAKE) win32-remove-setup-dlls
	cmd /c racket\src\worksp\build-at racket\src\worksp ..\..\..\build\config $(WIN32_BUILD_LEVEL) $(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)
win32-remove-setup-dlls:
	IF EXIST racket\lib\longdouble.dll cmd /c del racket\lib\longdouble.dll
	IF EXIST racket\lib\libiconv-2.dll cmd /c del racket\lib\libiconv-2.dll
	IF EXIST racket\lib\iconv.dll cmd /c del racket\lib\iconv.dll
	IF EXIST racket\lib\libeay32.dll cmd /c del racket\lib\libeay32.dll
	IF EXIST racket\lib\ssleay32.dll cmd /c del racket\lib\ssleay32.dll
racket/src/build/Makefile: racket/src/$(SRC_MAKEFILE_CONFIG) racket/src/Makefile.in
	mkdir -p racket/src/build
	cd racket/src/build && ../$(SRC_MAKEFILE_CONFIG) $(CONFIGURE_ARGS_qq) $(MORE_CONFIGURE_ARGS) $(CONFIG_IN_PLACE_ARGS)
native-for-cross:
	mkdir -p racket/src/build/cross
	$(MAKE) racket/src/build/cross/Makefile MORE_CROSS_CONFIGURE_ARGS="$(MORE_CROSS_CONFIGURE_ARGS)"
	cd racket/src/build/cross && $(MAKE) reconfigure MORE_CONFIGURE_ARGS="$(MORE_CROSS_CONFIGURE_ARGS)"
	cd racket/src/build/cross/racket && $(MAKE)
racket/src/build/cross/Makefile: racket/src/configure racket/src/cfg-bc racket/src/Makefile.in
	cd racket/src/build/cross && ../../configure $(MORE_CROSS_CONFIGURE_ARGS)
cs:
	$(MAKE) cs-in-place SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-cs:
	$(MAKE) win32-cs-in-place DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-in-place:
	$(MAKE) in-place VM=cs SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-cs-in-place:
	$(MAKE) win32-in-place VM=cs DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-as-is:
	$(MAKE) as-is VM=cs SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" CPUS="$(CPUS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-cs-as-is:
	$(MAKE) win32-as-is VM=cs RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-unix-style:
	$(MAKE) unix-style VM=cs SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" PREFIX="$(PREFIX)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" DESTDIR="$(DESTDIR)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-minimal-in-place:
	$(MAKE) cs-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) cs-minimal-in-place-after-base$(CS_CROSS_SUFFIX) DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" PKGS="$(PKGS)" PKGS_CATALOG="$(PKGS_CATALOG)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-cs-minimal-in-place:
	$(MAKE) win32-cs-base RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
	$(MAKE) plain-minimal-in-place-after-base PLAIN_RACKET=racket\racket$(RACKETCS_SUFFIX) DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" PKGS="$(PKGS)" PKGS_CATALOG="$(PKGS_CATALOG)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-skip-in-place:
	$(MAKE) cs-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-cs-skip-in-place:
	$(MAKE) win32-cs-base RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
cs-in-place-setup:
	$(MAKE) plain-in-place-setup PLAIN_RACKET=racket/bin/racket$(RACKETCS_SUFFIX) IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-cs-in-place-setup:
	$(MAKE) plain-in-place-setup PLAIN_RACKET=racket\racket$(RACKETCS_SUFFIX) IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-base:
	$(MAKE) maybe-fetch-pb RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)"
	$(MAKE) racket/src/build/cs/c/Makefile CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)"
	cd racket/src/build/cs/c && $(MAKE)
	$(MAKE) base-config
	cd racket/src/build/cs/c && $(MAKE) install CS_INSTALLED=$(RACKETCS_SUFFIX)   SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)"  PLT_SETUP_OPTIONS="$(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
racket/src/build/cs/c/Makefile: racket/src/cs/c/configure racket/src/cs/c/Makefile.in racket/src/cfg-cs
	mkdir -p cd racket/src/build/cs/c
	cd racket/src/build/cs/c && ../../../cs/c/configure $(CONFIGURE_ARGS_qq) $(MORE_CONFIGURE_ARGS) $(CONFIG_IN_PLACE_ARGS)
cs-minimal-in-place-after-base:
	$(MAKE) plain-minimal-in-place-after-base PLAIN_RACKET=racket/bin/racket$(RACKETCS_SUFFIX) DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" PKGS="$(PKGS)" PKGS_CATALOG="$(PKGS_CATALOG)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
cs-minimal-in-place-after-base-cross:
	$(MAKE) plain-minimal-in-place-after-base PLAIN_RACKET="$(RACKET_FOR_BUILD)" PLT_SETUP_OPTIONS="--no-pkg-deps $(PLT_SETUP_OPTIONS)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" PKGS_CONFIG="$(PKGS_CONFIG)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" PKGS="$(PKGS)" PKGS_CATALOG="$(PKGS_CATALOG)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
no-fetch-pb:
	echo done
fetch-pb:
	if [ "$(EXTRA_REPOS_BASE)" = "" ] ;           then $(MAKE) fetch-pb-from ;           else $(MAKE) fetch-pb-from PB_REPO="$(EXTRA_REPOS_BASE)pb/.git" ; fi
maybe-fetch-pb:
	if [ "$(RACKET_FOR_BOOTFILES)" = "" ] ;           then $(MAKE) fetch-pb EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" ; fi
fetch-pb-from:
	mkdir -p racket/src/ChezScheme/boot
	if [ ! -d racket/src/ChezScheme/boot/pb ] ; 	  then git clone -q -b  circa-7.8.0.6-1  https://github.com/racket/pb  racket/src/ChezScheme/boot/pb ; 	  else cd  racket/src/ChezScheme/boot/pb && git fetch -q origin  circa-7.8.0.6-1 ; fi
	cd  racket/src/ChezScheme/boot/pb && git checkout -q  circa-7.8.0.6-1
pb-stage:
	cd  racket/src/ChezScheme/boot/pb && git branch  circa-7.8.0.6-1
	cd  racket/src/ChezScheme/boot/pb && git checkout  circa-7.8.0.6-1
	cd  racket/src/ChezScheme/boot/pb && git add . && git commit --amend -m "new build"
pb-push:
	git push -u origin  circa-7.8.0.6-1
win32-cs-base:
	IF "$(RACKET_FOR_BUILD)" == "" $(MAKE) win32-bc-then-cs-base SETUP_BOOT_MODE=--boot WIN32_BUILD_LEVEL=3m PLAIN_RACKET=racket\racket3m RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
	IF not "$(RACKET_FOR_BUILD)" == "" $(MAKE) win32-just-cs-base SETUP_BOOT_MODE=--chain RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
win32-bc-then-cs-base:
	$(MAKE) win32-bc-base PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" JOB_OPTIONS="$(JOB_OPTIONS)"
	$(MAKE) win32-just-cs-base RACKET_FOR_BUILD="$(PLAIN_RACKET)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SETUP_BOOT_MODE="$(SETUP_BOOT_MODE)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
win32-just-cs-base:
	IF NOT EXIST racket\src\build cmd /c mkdir racket\src\build
	cmd /c $(RACKET_FOR_BUILD)  -O "info@compiler/cm"                     -l- setup $(SETUP_BOOT_MODE) racket/src/setup-go.rkt racket/src/build/compiled                     ignored racket/src/build/ignored.d racket\src\worksp\csbuild.rkt  --pull                      --racketcs-suffix "$(RACKETCS_SUFFIX)" $(DISABLE_STATIC_LIBS)                      --boot-mode "$(SETUP_BOOT_MODE)"                      --extra-repos-base "$(EXTRA_REPOS_BASE)"                      -- $(GIT_CLONE_ARGS_qq)
	IF NOT EXIST build\config cmd /c mkdir build\config
	cmd /c echo #hash((links-search-files . ())) > build\config\config.rktd
	racket\racket$(RACKETCS_SUFFIX) -G build\config -N raco -l- raco setup $(JOB_OPTIONS) $(PLT_SETUP_OPTIONS)
native-cs-for-cross:
	$(MAKE) maybe-fetch-pb RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)"
	mkdir -p racket/src/build/cross/cs/c
	$(MAKE) racket/src/build/cross/cs/c/Makefile
	cd racket/src/build/cross/cs/c && $(MAKE) reconfigure
	cd racket/src/build/cross/cs/c && $(MAKE)
racket/src/build/cross/cs/c/Makefile: racket/src/cs/c/configure racket/src/cs/c/Makefile.in
	cd racket/src/build/cross/cs/c; ../../../../cs/c/configure --enable-csdefault
both:
	$(MAKE) bc IN_PLACE_SETUP_OPTIONS="--error-out build/step" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) also-cs IN_PLACE_SETUP_OPTIONS="--error-in build/step" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
plain-also:
	$(MAKE) $(VM) INITIAL_SETUP_MODE=skip PLT_SETUP_OPTIONS="-D $(PLT_SETUP_OPTIONS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
also-cs:
	$(MAKE) plain-also VM=cs SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
also-bc:
	$(MAKE) plain-also VM=bc SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-both:
	$(MAKE) win32-bc DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" PKGS_CONFIG="$(PKGS_CONFIG)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) win32-also-cs SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-plain-also:
	$(MAKE) $(VM) INITIAL_SETUP_MODE=skip PLT_SETUP_OPTIONS="-D $(PLT_SETUP_OPTIONS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-also-cs:
	$(MAKE) win32-plain-also VM=cs SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
win32-also-bc:
	$(MAKE) win32-plain-also VM=bc SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DEFAULT_SRC_CATALOG="$(DEFAULT_SRC_CATALOG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" IN_PLACE_SETUP_OPTIONS="$(IN_PLACE_SETUP_OPTIONS)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" CS_CROSS_SUFFIX="$(CS_CROSS_SUFFIX)" PKGS_CONFIG="$(PKGS_CONFIG)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" CPUS="$(CPUS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" PKGS="$(PKGS)" RACKETBC_SUFFIX="$(RACKETBC_SUFFIX)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" PKGS_CATALOG="$(PKGS_CATALOG)" INITIAL_SETUP_MODE="$(INITIAL_SETUP_MODE)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
bootstrapped-repo:
	if [ "$(EXTRA_REPOS_BASE)" = "" ] ;          then $(MAKE) update-bootstrapped-normal GIT_UPDATE_ARGS_qq="$(GIT_UPDATE_ARGS_qq)" ;          else $(MAKE) update-bootstrapped-as-extra GIT_CLONE_ARGS_qq="" GIT_PULL_ARGS_qq="$(GIT_PULL_ARGS_qq)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" ; fi
update-bootstrapped-normal:
	git submodule -q init && git submodule -q update $(GIT_UPDATE_ARGS_qq)
update-bootstrapped-as-extra:
	if [ ! -d racket/src/bootstrapped ] ; 	 then cd racket/src && git clone -q $(GIT_CLONE_ARGS_qq) $(EXTRA_REPOS_BASE)bootstrapped/.git ; 	fi
	cd racket/src/bootstrapped && git pull -q $(GIT_PULL_ARGS_qq)
clean:
	@echo "No makefile support for cleaning. Instead, try"
	@echo "  git clean -d -x -f ."
	@exit 1
pkgs-catalog:
	 $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects $(PKGS_CATALOG) racket/share/pkgs-catalog pkgs racket/src/expander
	 $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects $(PKGS_CONFIG) "$(DEFAULT_SRC_CATALOG)" "$(SRC_CATALOG)"
	 $(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) -G racket/etc -X racket/collects racket/src/pkgs-check.rkt racket/share/pkgs-catalog
with-setup-flags:
	if [ "$(SERVER_COMPILE_MACHINE)" = "-M" ] ;          then $(MAKE) $(NEXT_TARGET) SETUP_MACHINE_FLAGS="-MCR `pwd`/build/zo:" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS) --enable-crossany" SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" USER_RACO="$(USER_RACO)" ;          else $(MAKE) $(NEXT_TARGET) SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)" ; fi
random:
	echo $(MORE_CONFIGURE_ARGS)
server:
	$(MAKE) with-setup-flags NEXT_TARGET=plain-server SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
plain-server:
	rm -rf build/zo
	$(MAKE) plain-base SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) server-from-base TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DOC_SEARCH="$(DOC_SEARCH)" PKGS="$(PKGS)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" JOB_OPTIONS="$(JOB_OPTIONS)" USER_RACO="$(USER_RACO)"
server-from-base:
	$(MAKE) build/site.rkt
	$(MAKE) stamp BUILD_STAMP="$(BUILD_STAMP)"
	$(MAKE) build-from-catalog TEST_PKGS="$(TEST_PKGS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" REQUIRED_PKGS="$(REQUIRED_PKGS)" DOC_SEARCH="$(DOC_SEARCH)" PKGS="$(PKGS)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" JOB_OPTIONS="$(JOB_OPTIONS)" USER_RACO="$(USER_RACO)"
	$(MAKE) origin-collects USER_RACKET="$(USER_RACKET)"
	$(MAKE) built-catalog PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" USER_RACKET="$(USER_RACKET)"
	$(MAKE) built-catalog-server SERVER_PORT="$(SERVER_PORT)" CONFIG_MODE_q="$(CONFIG_MODE_q)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)"
build/site.rkt:
	mkdir -p build
	echo "#lang distro-build/config" > build/site.rkt
	echo "(machine)" >> build/site.rkt
stamp:
	if [ "$(BUILD_STAMP)" = '' ] ;           then $(MAKE) stamp-as-inferred ;           else $(MAKE) stamp-as-given BUILD_STAMP="$(BUILD_STAMP)" ; fi
stamp-as-given:
	echo "$(BUILD_STAMP)" > build/stamp.txt
stamp-as-inferred:
	if [ -d ".git" ] ; then $(MAKE) stamp-from-git ; else $(MAKE) stamp-from-date ; fi
stamp-from-git:
	echo `date +"%Y%m%d"`-`git log -1 --pretty=format:%h` > build/stamp.txt
stamp-from-date:
	date +"%Y%m%d" > build/stamp.txt
build-from-catalog:
	rm -rf build/user
	rm -rf build/catalog-copy
	$(USER_RACO) pkg catalog-copy "$(SRC_CATALOG)" build/catalog-copy
	$(MAKE) server-cache-config USER_RACO="$(USER_RACO)"
	$(USER_RACO) pkg install --all-platforms $(SOURCE_USER_AUTO_q) $(REQUIRED_PKGS) $(DISTRO_BUILD_PKGS)
	$(MAKE) set-server-config CONFIG_MODE_q="$(CONFIG_MODE_q)" USER_RACKET="$(USER_RACKET)" DOC_SEARCH="$(DOC_SEARCH)"
	$(USER_RACKET) -l- distro-build/pkg-info -o build/pkgs.rktd build/catalog-copy
	$(USER_RACKET) -l distro-build/install-pkgs $(CONFIG_MODE_q) "$(PKGS) $(TEST_PKGS)" $(SOURCE_USER_AUTO_q) --all-platforms
	$(USER_RACO) setup --avoid-main $(JOB_OPTIONS)
server-cache-config:
	$(USER_RACO) pkg config -i --set download-cache-dir build/cache
	$(USER_RACO) pkg config -i --set download-cache-max-files 1023
	$(USER_RACO) pkg config -i --set download-cache-max-bytes 671088640
set-server-config:
	$(USER_RACKET) -l distro-build/set-server-config build/user/config/config.rktd $(CONFIG_MODE_q) "" "" "$(DOC_SEARCH)" ""
origin-collects:
	$(USER_RACKET) -l distro-build/pack-collects
built-catalog:
	$(USER_RACKET) -l- distro-build/pack-built $(PACK_BUILT_OPTIONS) build/pkgs.rktd
built-catalog-server:
	if [ -d ".git" ]; then git update-server-info ; fi
	$(USER_RACKET) -l distro-build/serve-catalog $(CONFIG_MODE_q) "$(SERVER_HOSTS)" $(SERVER_PORT) $(USER_RACKET) 
binary-catalog:
	$(USER_RACKET) -l- distro-build/pack-built --mode binary build/pkgs.rktd
binary-catalog-server:
	$(USER_RACKET) -l- distro-build/serve-catalog --mode binary $(CONFIG_MODE_q) "$(SERVER_HOSTS)" $(SERVER_PORT)
client:
	if [ ! -d build/log ] ; then rm -rf build/user ; fi
	$(MAKE) $(CLIENT_BASE) MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS) $(DISABLE_STATIC_LIBS)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" CPUS="$(CPUS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VM="$(VM)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(MAKE) distro-build-from-server REMOTE_USER_AUTO="$(REMOTE_USER_AUTO)" USER_RACO="$(USER_RACO)"
	$(MAKE) $(BUNDLE_FROM_SERVER_TARGET) SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SERVER_COLLECTS_PATH="$(SERVER_COLLECTS_PATH)" BUNDLE_RACO_FLAGS="$(BUNDLE_RACO_FLAGS)" IN_BUNDLE_RACO="$(IN_BUNDLE_RACO)" PKG_SOURCE_MODE="$(PKG_SOURCE_MODE)" COPY_ARGS="$(COPY_ARGS)" UNPACK_COLLECTS_FLAGS="$(UNPACK_COLLECTS_FLAGS)" PLAIN_RACKET="$(PLAIN_RACKET)" USER_RACKET="$(USER_RACKET)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" REMOTE_INST_AUTO="$(REMOTE_INST_AUTO)" PKGS="$(PKGS)" SVR_PRT="$(SVR_PRT)" RECOMPILE_OPTIONS="$(RECOMPILE_OPTIONS)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)"
	$(USER_RACKET) -l distro-build/set-config  $(BUNDLE_CONFIG) "$(INSTALL_NAME)" "$(BUILD_STAMP)" "$(DOC_SEARCH)" $(DIST_CATALOGS_q)
	$(MAKE) installer-from-bundle DIST_DESC="$(DIST_DESC)" DIST_DIR="$(DIST_DIR)" INSTALLER_PRE_PROCESS_BASE64="$(INSTALLER_PRE_PROCESS_BASE64)" DIST_SUFFIX="$(DIST_SUFFIX)" DIST_BASE="$(DIST_BASE)" OSSLSIGNCODE_ARGS_BASE64="$(OSSLSIGNCODE_ARGS_BASE64)" USER_RACKET="$(USER_RACKET)" INSTALLER_OPTIONS="$(INSTALLER_OPTIONS)" INSTALLER_POST_PROCESS_BASE64="$(INSTALLER_POST_PROCESS_BASE64)" SOURCE_MODE="$(SOURCE_MODE)" TGZ_MODE="$(TGZ_MODE)" UPLOAD="$(UPLOAD)" RELEASE_MODE="$(RELEASE_MODE)" SIGN_IDENTITY="$(SIGN_IDENTITY)" DIST_NAME="$(DIST_NAME)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" MAC_PKG_MODE="$(MAC_PKG_MODE)" README="$(README)"
win32-client:
	IF EXIST build\user cmd /c del /f /s /q build\user
	$(MAKE) $(WIN32_CLIENT_BASE) RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" RACKET_FOR_BUILD="$(RACKET_FOR_BUILD)" GIT_CLONE_ARGS_qq="$(GIT_CLONE_ARGS_qq)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" WIN32_BUILD_LEVEL="$(WIN32_BUILD_LEVEL)" VM="$(VM)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)"
	$(MAKE) win32-distro-build-from-server REMOTE_USER_AUTO="$(REMOTE_USER_AUTO)" WIN32_RACO="$(WIN32_RACO)"
	$(MAKE) win32-bundle-from-server SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SERVER_COLLECTS_PATH="$(SERVER_COLLECTS_PATH)" PKG_SOURCE_MODE="$(PKG_SOURCE_MODE)" UNPACK_COLLECTS_FLAGS="$(UNPACK_COLLECTS_FLAGS)" WIN32_IN_BUNDLE_RACO="$(WIN32_IN_BUNDLE_RACO)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" WIN32_RACKET="$(WIN32_RACKET)" REMOTE_INST_AUTO="$(REMOTE_INST_AUTO)" PKGS="$(PKGS)" SVR_PRT="$(SVR_PRT)"
	$(WIN32_RACKET) -l distro-build/set-config  $(BUNDLE_CONFIG) "$(INSTALL_NAME)" "$(BUILD_STAMP)" "$(DOC_SEARCH)" $(DIST_CATALOGS_q)
	$(MAKE) win32-installer-from-bundle DIST_DESC="$(DIST_DESC)" DIST_DIR="$(DIST_DIR)" INSTALLER_PRE_PROCESS_BASE64="$(INSTALLER_PRE_PROCESS_BASE64)" DIST_SUFFIX="$(DIST_SUFFIX)" DIST_BASE="$(DIST_BASE)" OSSLSIGNCODE_ARGS_BASE64="$(OSSLSIGNCODE_ARGS_BASE64)" INSTALLER_OPTIONS="$(INSTALLER_OPTIONS)" INSTALLER_POST_PROCESS_BASE64="$(INSTALLER_POST_PROCESS_BASE64)" SOURCE_MODE="$(SOURCE_MODE)" WIN32_RACKET="$(WIN32_RACKET)" TGZ_MODE="$(TGZ_MODE)" UPLOAD="$(UPLOAD)" RELEASE_MODE="$(RELEASE_MODE)" SIGN_IDENTITY="$(SIGN_IDENTITY)" DIST_NAME="$(DIST_NAME)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" MAC_PKG_MODE="$(MAC_PKG_MODE)" README="$(README)"
client-compile-any:
	$(MAKE) client SETUP_MACHINE_FLAGS="-MCR `pwd`/build/zo:" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS) --enable-crossany" BUNDLE_FROM_SERVER_TARGET=bundle-cross-from-server SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" DIST_DESC="$(DIST_DESC)" SERVER_COLLECTS_PATH="$(SERVER_COLLECTS_PATH)" BUNDLE_RACO_FLAGS="$(BUNDLE_RACO_FLAGS)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" DIST_DIR="$(DIST_DIR)" IN_BUNDLE_RACO="$(IN_BUNDLE_RACO)" PKG_SOURCE_MODE="$(PKG_SOURCE_MODE)" COPY_ARGS="$(COPY_ARGS)" CLIENT_BASE="$(CLIENT_BASE)" INSTALLER_PRE_PROCESS_BASE64="$(INSTALLER_PRE_PROCESS_BASE64)" DIST_SUFFIX="$(DIST_SUFFIX)" DIST_BASE="$(DIST_BASE)" OSSLSIGNCODE_ARGS_BASE64="$(OSSLSIGNCODE_ARGS_BASE64)" UNPACK_COLLECTS_FLAGS="$(UNPACK_COLLECTS_FLAGS)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" PLAIN_RACKET="$(PLAIN_RACKET)" USER_RACKET="$(USER_RACKET)" INSTALLER_OPTIONS="$(INSTALLER_OPTIONS)" CPUS="$(CPUS)" INSTALLER_POST_PROCESS_BASE64="$(INSTALLER_POST_PROCESS_BASE64)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" BUNDLE_CONFIG="$(BUNDLE_CONFIG)" INSTALL_NAME="$(INSTALL_NAME)" TGZ_MODE="$(TGZ_MODE)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" UPLOAD="$(UPLOAD)" REMOTE_INST_AUTO="$(REMOTE_INST_AUTO)" DIST_CATALOGS_q="$(DIST_CATALOGS_q)" DISABLE_STATIC_LIBS="$(DISABLE_STATIC_LIBS)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" SIGN_IDENTITY="$(SIGN_IDENTITY)" DIST_NAME="$(DIST_NAME)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" SVR_PRT="$(SVR_PRT)" VM="$(VM)" RECOMPILE_OPTIONS="$(RECOMPILE_OPTIONS)" MAC_PKG_MODE="$(MAC_PKG_MODE)" REMOTE_USER_AUTO="$(REMOTE_USER_AUTO)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" README="$(README)" JOB_OPTIONS="$(JOB_OPTIONS)" USER_RACO="$(USER_RACO)"
distro-build-from-server:
	$(USER_RACO) pkg install $(REMOTE_USER_AUTO) distro-build-client
bundle-from-server:
	rm -rf bundle
	mkdir -p bundle/racket
	$(USER_RACKET) -l setup/unixstyle-install bundle racket bundle/racket
	$(USER_RACKET) -l setup/winstrip bundle/racket
	$(USER_RACKET) -l setup/winvers-change bundle/racket
	$(USER_RACKET) -l- distro-build/unpack-collects $(UNPACK_COLLECTS_FLAGS) $(SERVER_URL_SCHEME)://$(SVR_PRT)/$(SERVER_COLLECTS_PATH)
	$(IN_BUNDLE_RACO) setup --no-user $(JOB_OPTIONS) $(RECOMPILE_OPTIONS)
	$(IN_BUNDLE_RACO) pkg install $(REMOTE_INST_AUTO) $(PKG_SOURCE_MODE) $(REQUIRED_PKGS)
	$(IN_BUNDLE_RACO) pkg install $(REMOTE_INST_AUTO) $(PKG_SOURCE_MODE) $(PKGS)
	$(USER_RACKET) -l setup/unixstyle-install post-adjust "$(SOURCE_MODE)" "$(PKG_SOURCE_MODE)" racket bundle/racket
bundle-cross-from-server:
	rm -rf "build/zo`pwd`/bundle"
	$(MAKE) bundle-from-server SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SERVER_COLLECTS_PATH="$(SERVER_COLLECTS_PATH)" IN_BUNDLE_RACO="$(IN_BUNDLE_RACO)" PKG_SOURCE_MODE="$(PKG_SOURCE_MODE)" UNPACK_COLLECTS_FLAGS="$(UNPACK_COLLECTS_FLAGS)" USER_RACKET="$(USER_RACKET)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" REMOTE_INST_AUTO="$(REMOTE_INST_AUTO)" PKGS="$(PKGS)" SVR_PRT="$(SVR_PRT)" RECOMPILE_OPTIONS="$(RECOMPILE_OPTIONS)" JOB_OPTIONS="$(JOB_OPTIONS)" $(COPY_ARGS) IN_BUNDLE_RACO="$(PLAIN_RACKET) $(SETUP_MACHINE_FLAGS) $(BUNDLE_RACO_FLAGS)"
installer-from-bundle:
	$(USER_RACKET) -l- distro-build/installer   --readme "$(README)" --upload "$(UPLOAD)" --desc "$(DIST_DESC)" $(RELEASE_MODE) $(SOURCE_MODE) $(VERSIONLESS_MODE)                $(MAC_PKG_MODE) $(TGZ_MODE) --packed-options "$(INSTALLER_OPTIONS)"                --pre-process "$(INSTALLER_PRE_PROCESS_BASE64)"                --post-process "$(INSTALLER_POST_PROCESS_BASE64)"                "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR) "$(DIST_SUFFIX)"                "$(SIGN_IDENTITY)" "$(OSSLSIGNCODE_ARGS_BASE64)"
win32-distro-build-from-server:
	$(WIN32_RACO) pkg install $(REMOTE_USER_AUTO) distro-build-client
win32-bundle:
	IF EXIST bundle cmd /c rmdir /S /Q bundle
	cmd /c mkdir bundle\racket
	$(WIN32_RACKET) -l setup/unixstyle-install bundle$(SOURCE_MODE) racket bundle\racket
	$(WIN32_RACKET) -l setup/winstrip bundle\racket
	$(WIN32_RACKET) -l setup/winvers-change bundle\racket
win32-bundle-from-server:
	$(MAKE) win32-bundle SOURCE_MODE="$(SOURCE_MODE)" WIN32_RACKET="$(WIN32_RACKET)"
	$(WIN32_RACKET) -l- distro-build/unpack-collects $(UNPACK_COLLECTS_FLAGS) $(SERVER_URL_SCHEME)://$(SVR_PRT)/$(SERVER_COLLECTS_PATH)
	$(WIN32_IN_BUNDLE_RACO) setup --no-user -l racket/base
	$(WIN32_IN_BUNDLE_RACO) pkg install $(REMOTE_INST_AUTO) $(PKG_SOURCE_MODE) $(REQUIRED_PKGS)
	$(WIN32_IN_BUNDLE_RACO) pkg install $(REMOTE_INST_AUTO) $(PKG_SOURCE_MODE) $(PKGS)
win32-installer-from-bundle:
	$(WIN32_RACKET) -l- distro-build/installer   --readme "$(README)" --upload "$(UPLOAD)" --desc "$(DIST_DESC)" $(RELEASE_MODE) $(SOURCE_MODE) $(VERSIONLESS_MODE)                $(MAC_PKG_MODE) $(TGZ_MODE) --packed-options "$(INSTALLER_OPTIONS)"                --pre-process "$(INSTALLER_PRE_PROCESS_BASE64)"                --post-process "$(INSTALLER_POST_PROCESS_BASE64)"                "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR) "$(DIST_SUFFIX)"                "$(SIGN_IDENTITY)" "$(OSSLSIGNCODE_ARGS_BASE64)"
test-client:
	$(BUNDLE_RACO) pkg install $(REMOTE_INST_AUTO) $(PKG_SOURCE_MODE) $(TEST_PKGS)
	$(IN_BUNDLE_RACO) test $(TEST_ARGS_q)
win32-test-client:
	$(WIN32_BUNDLE_RACO) pkg install $(REMOTE_INST_AUTO) $(PKG_SOURCE_MODE) $(TEST_PKGS)
	$(WIN32_IN_BUNDLE_RACO) test $(TEST_ARGS_q)
client-from-site:
	$(MAKE) with-setup-flags NEXT_TARGET=plain-client-from-site SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
plain-client-from-site:
	make client  SERVER_CATALOG_PATH=$(SITE_PATH)catalog/ SERVER_COLLECTS_PATH=$(SITE_PATH)origin/                   DIST_CATALOGS_q='$(SERVER_URL_SCHEME)://$(SERVER):$(SERVER_PORT)/$(SITE_PATH)catalog/ ""'                   DOC_SEARCH="$(SERVER_URL_SCHEME)://$(SERVER):$(SERVER_PORT)/$(SITE_PATH)doc/local-redirect/index.html"                   $(PROP_ARGS)
installers:
	rm -rf build/installers
	$(MAKE) server SERVE_DURING_CMD_qq=' -l- distro-build/drive-clients $(DRIVE_DESCRIBE)  $(RELEASE_MODE) $(VERSIONLESS_MODE) $(SOURCE_MODE)                 $(CLEAN_MODE) $(SERVER_COMPILE_MACHINE) "$(CONFIG)" "$(CONFIG_MODE)"                 $(SERVER) $(SERVER_PORT) "$(SERVER_HOSTS)"                 "$(PKGS)" "$(DOC_SEARCH)" "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR)' SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
installers-from-built:
	$(MAKE) with-setup-flags NEXT_TARGET=plain-installers-from-built SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
plain-installers-from-built:
	$(MAKE) built-catalog-server SERVE_DURING_CMD_qq=' -l- distro-build/drive-clients $(DRIVE_DESCRIBE)  $(RELEASE_MODE) $(VERSIONLESS_MODE) $(SOURCE_MODE)                 $(CLEAN_MODE) $(SERVER_COMPILE_MACHINE) "$(CONFIG)" "$(CONFIG_MODE)"                 $(SERVER) $(SERVER_PORT) "$(SERVER_HOSTS)"                 "$(PKGS)" "$(DOC_SEARCH)" "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR)' SERVER_PORT="$(SERVER_PORT)" CONFIG_MODE_q="$(CONFIG_MODE_q)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)"
drive-clients:
	$(PLAIN_RACKET)  -l- distro-build/drive-clients $(DRIVE_DESCRIBE)  $(RELEASE_MODE) $(VERSIONLESS_MODE) $(SOURCE_MODE)                 $(CLEAN_MODE) $(SERVER_COMPILE_MACHINE) "$(CONFIG)" "$(CONFIG_MODE)"                 $(SERVER) $(SERVER_PORT) "$(SERVER_HOSTS)"                 "$(PKGS)" "$(DOC_SEARCH)" "$(DIST_NAME)" $(DIST_BASE) $(DIST_DIR)
describe-clients:
	$(MAKE) drive-clients DRIVE_DESCRIBE=--describe CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" SERVER_PORT="$(SERVER_PORT)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" PLAIN_RACKET="$(PLAIN_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" SOURCE_MODE="$(SOURCE_MODE)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)"
site:
	$(MAKE) installers SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
	$(MAKE) site-from-installers SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
site-from-installers:
	$(MAKE) with-setup-flags NEXT_TARGET=plain-site-from-installers SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
plain-site-from-installers:
	rm -rf build/docs
	rm -rf "build/zo`pwd`/build/docs"
	$(USER_RACKET) -l- distro-build/install-for-docs build/docs $(CONFIG_MODE_q) "$(PKGS)" $(DOC_CATALOGS)
	$(USER_RACKET) -l- distro-build/assemble-site $(CONFIG_MODE_q)
snapshot-site:
	$(MAKE) site SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
	$(MAKE) snapshot-at-site SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
snapshot-at-site:
	$(MAKE) with-setup-flags NEXT_TARGET=plain-snapshot-at-site SERVER_URL_SCHEME="$(SERVER_URL_SCHEME)" SELF_ROOT_CONFIG_FLAG="$(SELF_ROOT_CONFIG_FLAG)" SITE_PATH="$(SITE_PATH)" RACKETCS_SUFFIX="$(RACKETCS_SUFFIX)" CONFIG="$(CONFIG)" DIST_DIR="$(DIST_DIR)" SERVER="$(SERVER)" TEST_PKGS="$(TEST_PKGS)" SERVER_PORT="$(SERVER_PORT)" PROP_ARGS="$(PROP_ARGS)" PACK_BUILT_OPTIONS="$(PACK_BUILT_OPTIONS)" CONFIG_MODE_q="$(CONFIG_MODE_q)" DIST_BASE="$(DIST_BASE)" CLEAN_MODE="$(CLEAN_MODE)" SOURCE_USER_AUTO_q="$(SOURCE_USER_AUTO_q)" BUILD_STAMP="$(BUILD_STAMP)" PLT_SETUP_OPTIONS="$(PLT_SETUP_OPTIONS)" SRC_CATALOG="$(SRC_CATALOG)" USER_RACKET="$(USER_RACKET)" SERVER_HOSTS="$(SERVER_HOSTS)" DRIVE_DESCRIBE="$(DRIVE_DESCRIBE)" SOURCE_MODE="$(SOURCE_MODE)" REQUIRED_PKGS="$(REQUIRED_PKGS)" RACKET_FOR_BOOTFILES="$(RACKET_FOR_BOOTFILES)" RELEASE_MODE="$(RELEASE_MODE)" DOC_SEARCH="$(DOC_SEARCH)" DIST_NAME="$(DIST_NAME)" DOC_CATALOGS="$(DOC_CATALOGS)" CONFIG_IN_PLACE_ARGS="$(CONFIG_IN_PLACE_ARGS)" VERSIONLESS_MODE="$(VERSIONLESS_MODE)" PKGS="$(PKGS)" CONFIG_MODE="$(CONFIG_MODE)" VM="$(VM)" MORE_CONFIGURE_ARGS="$(MORE_CONFIGURE_ARGS)" SERVER_COMPILE_MACHINE="$(SERVER_COMPILE_MACHINE)" DISTRO_BUILD_PKGS="$(DISTRO_BUILD_PKGS)" EXTRA_REPOS_BASE="$(EXTRA_REPOS_BASE)" JOB_OPTIONS="$(JOB_OPTIONS)" SETUP_MACHINE_FLAGS="$(SETUP_MACHINE_FLAGS)" USER_RACO="$(USER_RACO)"
plain-snapshot-at-site:
	$(USER_RACKET) -l- distro-build/manage-snapshots $(CONFIG_MODE_q)
makemake: .makefile racket/src/makemake.rkt
	racket racket/src/makemake.rkt .makefile > Makefile
