language: c

sudo: required

os:
  - linux
  - osx

env:
  global:
    - PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
  matrix:
    - SCHEME=chez
    - SCHEME=ikarus
    - SCHEME=vicare

matrix:
  exclude:
    - os: osx
      env: SCHEME=vicare

addons:
  apt:
    packages:
      - libncurses5-dev
      - libgmp-dev
      - libffi-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libffi     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bzr        ; fi
  - ./.travis/install_scheme

script:
  .travis/run_tests
